[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
base = "https://mainnet.base.org"
base-sepolia = "https://sepolia.base.org"

[etherscan]
base = { key = "YOUR_API_KEY" }
base-sepolia = { key = "YOUR_API_KEY" }

# Configuración específica para Base
[profile.base]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"
optimizer = true
optimizer_runs = 200
via_ir = true
